export const siteContent = {
  appName: "Indian Dreams",
  menuItems: [
    { name: "Home", iconName: "Home" },
    { name: "Services", iconName: "Service" },
    { name: "Packages", iconName: "TravelPackage" },
    { name: "Locations", iconName: "TravelLocations" },
    { name: "About", iconName: "AboutInfo" },
  ],
  heroTitle: "Travel..  Experience..  Live",
  heroParagraph:
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit aliquid deserunt doloribus quod nemo voluptatum autem aspernatur perspiciatis minus. Odio numquam illum doloremque in eius esse. Autem quasi repellat velit!",
  services: [
    {
      title: "Explore Best Near You",
      desc:
        "Enjy your trip by find best things around you like Locations, hotels, Transportation, Guides etc.",
    },
    {
      title: "Safety First",
      desc:
        "We are ensuring Covid safe environment and our first and last priority is your safety",
    },
    {
      title: "Best Prices & Offers",
      desc:
        "Book early for exclusive offers and prices. keep in touch with us to know more.",
    },
    {
      title: "Flexible Payment",
      desc:
        "We will accept payment through different mediums to ensure smooth transaction experience.",
    },
  ],

  topPackages: {
    holiday: [
      {
        id: 1,
        name: "Goa",
        price: 10000,
        time: "2N-2D",
        url: require("../Assets/packages/goa.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 2,
        name: "Manali",
        price: 20000,
        time: "2N-3D",
        url: require("../Assets/packages/manali.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 3,
        name: "Varanasi",
        price: 10000,
        time: "1N-2D",
        url: require("../Assets/packages/varanasi.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 4,
        name: "Mussorie",
        price: 15000,
        time: "2N-3D",
        url: require("../Assets/packages/mussorie.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 5,
        name: "shimla",
        price: 22000,
        time: "3N-2D",
        url: require("../Assets/packages/shimla.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 6,
        name: "gangtop",
        price: 35000,
        time: "3N-3D",
        url: require("../Assets/packages/gangtop.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
    ],
    family: [
      {
        id: 1,
        name: "kerala",
        price: 20000,
        time: "2N-3D",
        url: require("../Assets/packages/kerala.jpg"),
        locations: ["Wayanad", "idukki", "Alleppey"],
      },
      {
        id: 2,
        name: "kashmir",
        price: 25000,
        time: "2N-3D",
        url: require("../Assets/packages/kashmir.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 3,
        name: "North-East",
        price: 32000,
        time: "3N-4D",
        url: require("../Assets/packages/North-East.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 4,
        name: "Mussorie",
        price: 20000,
        time: "3N-3D",
        url: require("../Assets/packages/mussorie.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 5,
        name: "ooty",
        price: 27000,
        time: "2N-3D",
        url: require("../Assets/packages/ooty.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 6,
        name: "shimla",
        price: 17000,
        time: "1N-2D",
        url: require("../Assets/packages/shimla.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
    ],
    honeymoon: [
      {
        id: 1,
        name: "Andaman",
        price: 50000,
        time: "4N-5D",
        url: require("../Assets/packages/andaman.jpg"),
        locations: ["Wayanad", "idukki", "Alleppey"],
      },
      {
        id: 2,
        name: "Darjeeling",
        price: 55000,
        time: "5N-5D",
        url: require("../Assets/packages/darjeeling.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 3,
        name: "Lakshadweep",
        price: 44000,
        time: "3N-4D",
        url: require("../Assets/packages/lakshdweep.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 4,
        name: "Kashmir",
        price: 40000,
        time: "4N-3D",
        url: require("../Assets/packages/kashmir.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 5,
        name: "gangtop",
        price: 37000,
        time: "4N-3D",
        url: require("../Assets/packages/gangtop.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 6,
        name: "udaipur",
        price: 27000,
        time: "2N-3D",
        url: require("../Assets/packages/udaipur.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
    ],
    luxury: [
      {
        id: 1,
        name: "Goa",
        price: 58000,
        time: "2N-3D",
        url: require("../Assets/packages/goa.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 2,
        name: "Udaipur",
        price: 75000,
        time: "2N-2D",
        url: require("../Assets/packages/udaipur_lux.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 3,
        name: "North-East",
        price: 64000,
        time: "4N-3D",
        url: require("../Assets/packages/North-East.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 4,
        name: "Kashmir",
        price: 70000,
        time: "4N-3D",
        url: require("../Assets/packages/kashmir.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 5,
        name: "Mussorie",
        price: 47000,
        time: "2N-3D",
        url: require("../Assets/packages/mussorie.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
      {
        id: 6,
        name: "Andaman",
        price: 99000,
        time: "6N-7D",
        url: require("../Assets/packages/andaman.jpg"),
        locations: [
          "Fontainhas",
          "Baga Beach",
          "Church of Our Lady Of Hope",
          "Saturday Night Market",
          "Palolem Beach",
        ],
      },
    ],
  },
};

export const devices = {
  mobileS: `(min-width: 320px)`,
  mobileM: `(min-width: 375px)`,
  mobileL: `(min-width: 425px)`,
  tabletM: `(min-width: 576px)`,
  tablet: `(min-width: 768px)`,
  tabletL: `(min-width: 900px)`,
  laptop: `(min-width: 1024px)`,
  laptopL: `(min-width: 1440px)`,
  desktop: `(min-width: 2000px)`,
};
